title: Faramandi Team Freelancers

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
    url: /portfolio
  - title: Testimonials
    url: /testimonials
  - title: Contact
    url: /contact

# Contact information
email: hello@faramandi.com
phone: "+98 123 456 7890"
instagram: "@faramandi_team"
linkedin: "faramandi-freelancers"